baseURL = 'https://patglanz.github.io/tech-blog/'
languageCode = 'de-de'
title = 'Pats Tech Blog'
theme = 'PaperMod'
canonifyURLs = true

[params]
env = 'production'
title = 'Pats Tech Blog'
description = 'Hardware, Home Assistant und technische Basteleien'
author = 'Patrick'
defaultTheme = 'auto'
showCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Gude, ich bin Pat."
subtitle = "Vom Graben in die Cloud – meine Smarthome- und DevOps-Abenteuer."
imageUrl = "images/loch.jpg"
imageWidth = 250  # Hier kannst du mit der Größe spielen (Standard ist 120)
imageHeight = 250 # Am besten den gleichen Wert nehmen, damit es rund bleibt
imageCover = true
imageTitle = "Vom Graben zum Smart Home"

[[params.profileMode.buttons]]
name = "Featured: Temperatursensor mit ESP32 bauen"
url = "posts/praeziser-temperatur-feuchte-sensor-home-assistant"

[[params.profileMode.buttons]]
name = "Zum Wasserzähler-Projekt"
url = "posts/wasserzaehler-home-assistant"

[[params.profileMode.buttons]]
name = "GitHub"
url = "https://github.com/patglanz"

[[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/patrick-glanz-829566b/"

    [[params.socialIcons]]
        name = "x" # Falls das Theme die neueste Version hat. Wenn kein Logo erscheint, nutze stattdessen "twitter"
        url = "https://x.com/GlanzPat"

[menu]
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "GitHub"
url = "https://github.com/patglanz/tech-blog"
weight = 20

[[menu.main]]
name = "Impressum"
url = "impressum"
weight = 30
