baseURL = 'https://patglanz.github.io/tech-blog/'
languageCode = 'de-de'
title = 'Pats Tech Blog'
theme = 'PaperMod'
canonifyURLs = true

[params]
env = 'production'
title = 'Pats Tech Blog'
description = 'Hardware, Home Assistant und technische Basteleien'
author = 'Patrick'
defaultTheme = 'auto'
showCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Gude, ich bin Pat."
subtitle = "Vom Graben bis zur Cloud – meine Smarthome- und DevOps-Abenteuer."
imageUrl = "images/loch.jpg"
imageCover = true
imageTitle = "Vom Graben zum Smart Home"

[[params.profileMode.buttons]]
name = "Zum Wasserzähler-Projekt"
url = "posts/wasserzaehler-home-assistant"

[[params.profileMode.buttons]]
name = "GitHub"
url = "https://github.com/patglanz"

[menu]
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "GitHub"
url = "https://github.com/patglanz/tech-blog"
weight = 20

[[menu.main]]
name = "Impressum"
url = "impressum"
weight = 30
